### PR TITLE
update readme and add a test

### PR DESCRIPTION
**Pull request by aimichal**
Changes:

* README updated to make it clearer what to expect, and how to submit.
* Added a test
* Added a valid predictions file.
* Made Python version more explicit
* Changed dependency of `sklearn` to `scikit-learn==0.24.0` to be more explicit.

I will build and publish the evaluator, and use it in Leaderboard to see what dummy/baseline score I get, then update the XXX in this PR.

@qiangning Or do you think another baseline/dummy file should be distributed? (For example, I see 0s and 1s as predictions for each of the questions; could all those be 0 or 1 as a real dummy baseline?)

Here's what I see when I run test.sh:

```
~/code/torque-evaluator ‹michalg/updates› $ ./test.sh
------------------------------
Building evaluator
------------------------------

Sending build context to Docker daemon  23.04kB
Step 1/7 : FROM library/python:3.8.7-buster
 ---> f5041c8ae6b1
Step 2/7 : ENV LC_ALL=C.UTF-8
 ---> Using cache
 ---> 91bc9a38ad5a
Step 3/7 : ENV LANG=C.UTF-8
 ---> Using cache
 ---> 894ff4b08e3c
Step 4/7 : COPY requirements.txt requirements.txt
 ---> Using cache
 ---> 6f5cee85f4bf
Step 5/7 : RUN pip3.8 install -r requirements.txt
 ---> Using cache
 ---> 6e17cde799a3
Step 6/7 : COPY . .
 ---> Using cache
 ---> 35675a6c25d8
Step 7/7 : CMD ["/bin/bash"]
 ---> Using cache
 ---> e22afb5f0e68
Successfully built e22afb5f0e68
Successfully tagged torque-evaluator:latest

------------------------------
Running evaluator
------------------------------

====Input Arguments====
{
  "labels_file": "/data/gold_small.json",
  "metrics_output_file": "/output/metrics.json",
  "preds_file": "/predictions/predictions_small.json"
}
=======================
the current eval positive class Micro F1 (Agg) is: 0.8889
the current eval positive class Macro F1 (Relaxed) is: 0.6667
the current eval positive class Macro F1 (Agg) is: 0.6667
the current eval exact match ratio (Relaxed) is: 0.6667
2 Clusters
the current eval clustered EM (Agg) is: 0.5000
the current eval clustered EM (Relaxed) is: 0.5000
the current eval clusrered F1 (max>=0.8) is: 0.5000

------------------------------
Metrics
------------------------------

Metrics obtained in file /var/folders/96/smk54_7d0gd8dt56rpdlhql40000gn/T/tmp.zHROtV0T/metrics.json:

{"F1": 0.6666666666666666, "EM": 0.6666666666666666, "C": 0.5}

Metrics match expected values!

Test passed.
```

### CODE REVIEW

**Comment by aimichal** [comment]
@qiangning Actually, if this code looks okay, can you publish the evaluator from this branch to the same place in Beaker as before? Then we won't have to change Leaderboard's config.

**Comment by aimichal** [comment]
@qiangning I've build and published it to use in Leaderboard (https://github.com/allenai/leaderboard/pull/1200) so no need to do anything.

Using it, I got a score which I've shown in the README here.

LMK if you'd rather use a "more dummy" prediction file with all 0s or all 1s.

**Comment by aimichal** [comment]
@qiangning This evaluator has been pushed to the production site, and I've confirmed predictions_dummy.json file scores as expected.

**Comment by qiangning** [comment]
Thanks Michal. It looks good to me. A more dummy prediction file is not needed from my perspective. I see you have a submission "xxxxx" with a "consistency" score of 0.9691. This submission "xxxxx" has the same Macro F1 and EM as Submission 655656, so it makes me wonder what's happening.

**Comment by aimichal** [comment]
> Thanks Michal. It looks good to me. A more dummy prediction file is not needed from my perspective.

👍 

Then I'll merge this.

> I see you have a submission "xxxxx" with a "consistency" score of 0.9691. This submission "xxxxx" has the same Macro F1 and EM as Submission 655656, so it makes me wonder what's happening.

Good eyes! 🦅 

What's happening is that ... I hacked the staging leaderboard database 🤓 to get scores that let me confirm that the sorting order of the "Systems ordered by consistency" graph needed to be fixed:  https://github.com/allenai/leaderboard/commit/9608f91d8252b73a428df8bb7e87ae2a39ccf694

**Comment by qiangning** [comment]
Ok, it's good to know that it was not a system that would make my dataset
meaningless ;)

**Comment by qiangning** [comment]
Oh btw Michal, will you delete the two test submissions currently published
on the LB?

**Comment by aimichal** [comment]
> Oh btw Michal, will you delete the two test submissions currently published on the LB?

https://leaderboard.allenai.org/torque/submissions/public has no published submissions.

If you mean the Staging site, then that's [not meant for public use](https://github.com/allenai/leaderboard/issues/1196) :-) Please don't share the URL to it. But yes, I have unpublished those two submissions there.

**Comment by qiangning** [comment]
Great!

**Pull request merged**
